### ISSUE TITLE
it should be Long instead of long

### ISSUE THREAD

**Issue by FuncGuy** [prasadus92/ecommerce-store#5]
https://github.com/prasadus92/ecommerce-store/blob/cec00448d9c3e6c6bfb09ba04b8753b16f2002c2/src/main/java/com/ecommerce/store/entities/dao/Product.java#L57

reference:

https://aodcoding.wordpress.com/2015/07/06/preventing-lost-updates-in-mongo-with-spring-optimistic-locking/

**Comment by prasadus92** [comment]
This shouldn't be a problem for Spring Data JPA.
Spring Data MongoDB requires `org.springframework.data.annotation.Version` and the field should be a non-primitive type as you mentioned (`Long` over `long`).
